name: deploy website preview
on:
  pull_request:
    branches:
      - main
    types:
      - labeled

jobs:
  deploy:
    if: github.event.label.name == 'approve to run'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: set up pr preview
        uses: amondnet/vercel-action@v20 # deploy
        id: vercel-action-prev
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          github-token: ${{ secrets.GITHUB_TOKEN }} # Optional
          vercel-org-id: ${{ secrets.ORG_ID }} # Required
          vercel-project-id: ${{ secrets.PROJECT_ID }} # Required
          working-directory: ./
          github-comment: false

      - name: preview-url
        run: |
          echo ${{ steps.vercel-action-prev.outputs.preview-url }}
